### ISSUE TITLE
Check for MFA on Root Acount

### ISSUE THREAD

**Issue by mccoyaoife** [aws/Trusted-Advisor-Tools#18]
I was hoping you could provide an example for the check-name MFA on Root Account along with sample payload as a cloudwatch event. Due to the fact any accounts I work in already have mfa enabled on the root, I am unable to generate a cloudwatch event that would be trigged upon the rule: 

{
  "source": [
    "aws.trustedadvisor"
  ],
  "detail-type": [
    "Trusted Advisor Check Item Refresh Notification"
  ],
  "detail": {
    "check-name": [
      "MFA on Root Account",
      "IAM Use"
    ]
  }
}

Thanks!

**Comment by tipuq** [comment]
Hi, sorry for the delayed response, here is a sample json that you could use to simulate the event:

{
   "version":"0",
   "id":"ca425f41-2d02-e401-e03f-ada1244d8c67",
   "detail-type":"Trusted Advisor Check Item Refresh Notification",
   "source":"aws.trustedadvisor",
   "account":"<accountId>",
   "time":"2019-06-21T00:08:55Z",
   "region":"us-east-1",
   "detail":{
      "check-name":"MFA on Root Account",
      "check-item-detail":{
         "Status":"Red",
         "Region":"us-east-1",
         "Reason":"MFA is not enabled on the root account"
      },
      "status":"ERROR",
      "uuid":"0c7e4887-282b-4e7e-8c68-26582e460b9a"
   }
}

You could you use a custom Cloud Watch action: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/AddEventsPutEvents.html
