### ISSUE TITLE
nodejs runtime out of support

### ISSUE THREAD

**Issue by hgoodrow** [aws/Trusted-Advisor-Tools#19]
The nodejs runtime for many of the examples are out of date.  They are based on nodejs 6.10 and they must be updated to nodejs 8.10 or 10.

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by tipuq** [comment]
Thank you for raising this issue. The nodejs based Cloud Formation templates have been updated.
