### ISSUE TITLE
There is a dependency issue in the ajv package

### ISSUE THREAD

**Issue by caiomarini98** [aws/Trusted-Advisor-Tools#47]
I'm trying to use the Eisenhower Matrix App in AWS Amplify Hosting, but having some issues with the ajv package.

When I install the ajv and run the `npm install` command, I receive the following error message: 
`npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.`

When I run `npm install ajv@6.9.1` to resolve it, I receive the following error message:
`npm WARN @apideck/better-ajv-errors@0.3.6 requires a peer of ajv@>=8 but none is installed. You must install peer dependencies yourself.`

I believe this is a co-dependency problem, but don't have any knowledge about Node.js. 
I am really excited to run this solution in my company, if you guys can help me with that, I would really appreciate it.

**Comment by tipuq** [comment]
fixed in https://github.com/aws/Trusted-Advisor-Tools/pull/48
